test_level_2
jina-ai/gptdeploy pull request #73
Opened 2023-04-29 23:59 UTC by florian-hoenicke

2023-04-30 11:43 UTC, JoanFM requested changes

2023-04-30 11:43 UTC, JoanFM commented on src/options/generate/generator.py
> +Note that if the test scenario must contain the full description of the concrete example in case it was mentioned in the microservice description.'''
does this sentence make sense?

2023-04-30 15:45 UTC, florian-hoenicke commented on src/options/generate/generator.py
> +Note that if the test scenario must contain the full description of the concrete example in case it was mentioned in the microservice description.'''
nice catch
The first if can go

2023-05-01 16:18 UTC, florian-hoenicke commented on src/options/generate/generator.py
> +        # I deactivated this because 3.5-turbo was halucinating packages that were not needed
@joschkabraun in case you have some ideas around this

2023-05-01 16:27 UTC, merged